"""
SQLAlchemy ORM models for the Kurukh-Hindi-English vocabulary dataset.

These models are for application-side querying only.
Schema source of truth: database/kurukh_hindi_english_dictionary_postgresql.sql

IMPORTANT:
- Do NOT call Base.metadata.create_all() anywhere.
- Do NOT use Alembic to generate or apply schema from these models.
- The database schema is created exclusively from the teammate SQL file.
- Column names, types, constraints, and FK rules mirror the SQL file exactly.
"""

from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.database import Base


# ── datasets ──────────────────────────────────────────────────────────────────

class Dataset(Base):
    """
    Mirrors the `datasets` table.

    CREATE TABLE datasets (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        dataset_name VARCHAR(255) NOT NULL,
        description TEXT,
        version VARCHAR(20) NOT NULL,
        date_compiled DATE,
        total_entries INTEGER CHECK (total_entries >= 0),
        total_categories INTEGER CHECK (total_categories >= 0),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    """

    __tablename__ = "datasets"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    dataset_name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    version: Mapped[str] = mapped_column(String(20), nullable=False)
    date_compiled: Mapped[date | None] = mapped_column(Date, nullable=True)
    total_entries: Mapped[int | None] = mapped_column(
        Integer,
        CheckConstraint("total_entries >= 0", name="datasets_total_entries_check"),
        nullable=True,
    )
    total_categories: Mapped[int | None] = mapped_column(
        Integer,
        CheckConstraint("total_categories >= 0", name="datasets_total_categories_check"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )

    # Relationship — one Dataset has many Categories (CASCADE delete in SQL)
    categories: Mapped[list[Category]] = relationship(
        "Category",
        back_populates="dataset",
        cascade="all, delete-orphan",
    )


# ── languages ─────────────────────────────────────────────────────────────────

class Language(Base):
    """
    Mirrors the `languages` table.

    CREATE TABLE languages (
        iso_639_3 CHAR(3) PRIMARY KEY,
        language_name VARCHAR(100) NOT NULL,
        script VARCHAR(100) NOT NULL
    );
    """

    __tablename__ = "languages"

    iso_639_3: Mapped[str] = mapped_column(String(3), primary_key=True)
    language_name: Mapped[str] = mapped_column(String(100), nullable=False)
    script: Mapped[str] = mapped_column(String(100), nullable=False)


# ── categories ────────────────────────────────────────────────────────────────

class Category(Base):
    """
    Mirrors the `categories` table.

    CREATE TABLE categories (
        id VARCHAR(100) PRIMARY KEY,
        dataset_id INTEGER NOT NULL,
        display_order INTEGER NOT NULL CHECK (display_order >= 0),
        title_hindi VARCHAR(255) NOT NULL,
        title_english VARCHAR(255) NOT NULL,
        entry_count INTEGER NOT NULL CHECK (entry_count >= 0),
        CONSTRAINT fk_categories_dataset
            FOREIGN KEY (dataset_id) REFERENCES datasets(id)
            ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT uq_category_order UNIQUE (dataset_id, display_order)
    );
    """

    __tablename__ = "categories"
    __table_args__ = (
        UniqueConstraint("dataset_id", "display_order", name="uq_category_order"),
    )

    id: Mapped[str] = mapped_column(String(100), primary_key=True)
    dataset_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("datasets.id", onupdate="CASCADE", ondelete="CASCADE"),
        nullable=False,
    )
    display_order: Mapped[int] = mapped_column(
        Integer,
        CheckConstraint("display_order >= 0", name="categories_display_order_check"),
        nullable=False,
    )
    title_hindi: Mapped[str] = mapped_column(String(255), nullable=False)
    title_english: Mapped[str] = mapped_column(String(255), nullable=False)
    entry_count: Mapped[int] = mapped_column(
        Integer,
        CheckConstraint("entry_count >= 0", name="categories_entry_count_check"),
        nullable=False,
    )

    # Relationships
    dataset: Mapped[Dataset] = relationship("Dataset", back_populates="categories")
    entries: Mapped[list[VocabularyEntry]] = relationship(
        "VocabularyEntry",
        back_populates="category",
    )


# ── vocabulary_entries ────────────────────────────────────────────────────────

class VocabularyEntry(Base):
    """
    Mirrors the `vocabulary_entries` table.

    CREATE TABLE vocabulary_entries (
        id VARCHAR(20) PRIMARY KEY,
        category_id VARCHAR(100) NOT NULL,
        kurukh VARCHAR(255) NOT NULL,
        hindi VARCHAR(255) NOT NULL,
        english VARCHAR(255) NOT NULL,
        part_of_speech VARCHAR(100),
        kurukh_romanized VARCHAR(255),
        audio_url TEXT,
        notes TEXT,
        verified_by_native_speaker BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT fk_entries_category
            FOREIGN KEY (category_id) REFERENCES categories(id)
            ON UPDATE CASCADE ON DELETE RESTRICT
    );

    Indexes (defined in SQL, not in ORM):
        idx_entries_category, idx_entries_kurukh, idx_entries_hindi,
        idx_entries_english, idx_entries_pos, idx_entries_verified
    """

    __tablename__ = "vocabulary_entries"

    id: Mapped[str] = mapped_column(String(20), primary_key=True)
    category_id: Mapped[str] = mapped_column(
        String(100),
        ForeignKey("categories.id", onupdate="CASCADE", ondelete="RESTRICT"),
        nullable=False,
    )
    kurukh: Mapped[str] = mapped_column(String(255), nullable=False)
    hindi: Mapped[str] = mapped_column(String(255), nullable=False)
    english: Mapped[str] = mapped_column(String(255), nullable=False)
    part_of_speech: Mapped[str | None] = mapped_column(String(100), nullable=True)
    kurukh_romanized: Mapped[str | None] = mapped_column(String(255), nullable=True)
    audio_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    verified_by_native_speaker: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="FALSE",
    )

    # Relationship
    category: Mapped[Category] = relationship("Category", back_populates="entries")
